### ISSUE TITLE
Support for http://onhax.net/

### ISSUE THREAD

**Issue by axarad** [HandyUserscripts/AntiAdware#11]
Hello and thank you for this wonderful script,
please add support for http://onhax.net/ , it's full of "Fake Download Buttons"
Thanks again and keep the great work!

**Comment by devnoname120** [comment]
The fake download button that you see are already hidden by extensions such as [µBlock](https://github.com/gorhill/uBlock#readme).

AntiAdware only blocks content that cannot be blocked by such extensions (or is currently not supported.)

Could you please provide me a screenshot, so that I can make sure that we are indeed talking about the same buttons?
