### ISSUE TITLE
improve support for uptobox.com?

### ISSUE THREAD

**Issue by axarad** [HandyUserscripts/AntiAdware#19]
First thank you for your efforts,
I want to ask you if you can optimize the script to take less time for hiding uptobox.com Adware (it's working but it takes some time compared to other websites) and also make download button position at the middle of page after hiding the download manager Adware (t's too down)
Thanks again for your time!

**Comment by devnoname120** [comment]
I will check this, but I am not sure that I am going to speed up the process.
The slowness is probably due to my script waiting for the page to be fully loaded before operating.
Fixing this would require to handle things differently (Mutation Observer), and I am not sure that it is worth doing.

Could you please provide me a screenshot of the mispositioning VS expected positioning? Uptobox does not provide adware in my country, so this is annoying for me to test (I need to employ a VPN).

**Comment by axarad** [comment]
Ok I understand,
Here are screenshots for misplaced Download Button:
![untitled1](https://cloud.githubusercontent.com/assets/10789454/7623445/54e442b8-f9d2-11e4-9326-115ec803e6b3.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/10789454/7623447/5c0e0682-f9d2-11e4-8a29-5365c93f68d2.png)

**Comment by devnoname120** [comment]
Please try this version, and tell me if this fixed your issue:
https://raw.githubusercontent.com/HandyUserscripts/AntiAdware/08047aefc47d7ea74d6acea21f9a538696e30a81/AntiAdware.user.js

**Comment by axarad** [comment]
The issue is fixed, thank you!

**Comment by devnoname120** [comment]
Alright, I'm releasing a new version, then. :)
